# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_child_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildIsToddler',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'verbose_name_plural': "Toddler's child",
                'indexes': [],
            },
            bases=('tree.child',),
        ),
        migrations.CreateModel(
            name='MyChilds',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'My childs',
                'indexes': [],
            },
            bases=('tree.child',),
        ),
        migrations.AddField(
            model_name='father',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
